version: '3.7'

services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coletivogloma-backend
    ports:
      - "3000:3000"
    environment:
      - HOST_DB=${HOST_DB}
      - PORT_DB=${PORT_DB}
      - USER_DB=${USER_DB}
      - PASSWORD_DB=${PASSWORD_DB}
      - NAME_DB=${NAME_DB}
      - OPENCAGE_API_KEY=${OPENCAGE_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - URL_DATABASE=${URL_DATABASE}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - MAIL_FROM=${MAIL_FROM}
    volumes:
      - logs:/app/logs
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers  # Montagem para acessar os logs do Docker

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.4
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.13.4
    container_name: filebeat
    user: root  # Define o usuário como root para evitar problemas de permissão
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml  # Monta o arquivo de configuração do Filebeat
      - /var/lib/docker/containers:/var/lib/docker/containers  # Permite acesso aos logs do Docker
      - /var/run/docker.sock:/var/run/docker.sock  # Permite que o Filebeat monitore os containers Docker
    depends_on:
      - nestjs  # Dependência do serviço NestJS

volumes:
  logs:
  esdata:
